In [4]:
!pip install scikit-learn

     |████████████████████████████████| 7.1MB 941kB/s eta 0:00:01
     |████████████████████████████████| 296kB 8.3MB/s eta 0:00:01
You should consider upgrading via the 'pip install --upgrade pip' command.


In [23]:
import numpy as np
from sklearn import datasets

In [24]:
def sigmoid(x):
    return 1 / (1+np.exp(-x))

In [25]:
x, y = datasets.make_classification(
        n_samples=100000,
        n_features=10,
        n_informative=10,
        n_redundant=0,
        n_clusters_per_class=1,
        random_state=1,
    )

In [26]:
sigmoid(x[0])

array([0.28204062, 0.48001021, 0.65810485, 0.28730602, 0.28590766,
       0.52771474, 0.72251768, 0.45813155, 0.95018282, 0.55966087])

In [27]:
x[0]

array([-0.9343619 , -0.08000181,  0.65486017, -0.90850418, -0.91534338,
        0.1109727 ,  0.95698467, -0.1678669 ,  2.94829452,  0.23978584])

In [28]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [29]:
sigmoid(x[0])

array([0.28204062, 0.48001021, 0.65810485, 0.28730602, 0.28590766,
       0.52771474, 0.72251768, 0.45813155, 0.95018282, 0.55966087])

In [30]:
x.shape

(100000, 10)

In [36]:
t = np.zeros(10)

In [39]:
t.transpose().shape

(10,)

In [40]:
predict()

array([[0.28204062, 0.48001021, 0.65810485, ..., 0.45813155, 0.95018282,
        0.55966087],
       [0.68568924, 0.55513233, 0.07255814, ..., 0.15697311, 0.58413051,
        0.06554959],
       [0.74951353, 0.93231703, 0.84691533, ..., 0.16849067, 0.64913613,
        0.13092171],
       ...,
       [0.69119705, 0.02430034, 0.45801112, ..., 0.07296397, 0.62909632,
        0.44762955],
       [0.31697336, 0.63289486, 0.24373276, ..., 0.52742801, 0.05944519,
        0.07412168],
       [0.74420322, 0.22135283, 0.99845559, ..., 0.15886827, 0.07411305,
        0.87716574]])

In [44]:
x.T[0]

array([-0.9343619 ,  0.78004233,  1.09601945, ...,  0.80572157,
       -0.76771611,  1.06793087])

In [45]:
y.size

100000

In [46]:
len(x)

100000